db:
  image: percona:latest
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: admin123
  volumes_from:
    - dbdata

nginx:
    image: yappabe/nginx
    ports:
        - 80:80
    links:
        - php
    volumes_from:
        - dbdata
    environment:
        DOCUMENT_ROOT: /var/www/app/web
        INDEX_FILE: app_dev.php
        PHP_FPM_SOCKET: php:9000

php:
    image: yappabe/php
    expose:
        - 9000:9000
    volumes_from:
        - dbdata
    links:
        - db:database

redis:
  image: redis:latest

dbdata:
  image: electrobits/docker-data-only
  volumes:
    - .:/var/www/app
    - /var/lib/mysql
    - /vendor

elastic:
  image: elasticsearch:latest
  ports:
    - "9200:9200"
  volumes_from:
    - dataelk

kopf:
  image: lmenezes/elasticsearch-kopf
  ports:
    - "8080:80"
  links:
    - elastic:elastic
  environment:
    - KOPF_SERVER_NAME=kopf.dev
    - KOPF_ES_SERVERS=elastic:9200

dataelk:
    image: busybox
    volumes:
        - /data
